### ISSUE TITLE
CORS errors when loading second level of dependencies

### ISSUE THREAD

**Issue by WiseBird** [broofa/npmgraph#3]
App at [http://npm.broofa.com/](http://npm.broofa.com/) can't load second level of dependencies due to multiple CORS errors:

![image](https://user-images.githubusercontent.com/1745378/34954985-8c1caf90-fa33-11e7-99fa-2c5fac3414ae.png)

**Comment by broofa** [comment]
What OS/browser are you running?

**Comment by WiseBird** [comment]
I tried crome and ff on linux

**Comment by broofa** [comment]
Hmm.  Looks like `registry.npmjs.cf` is down due to invalid SSL cert.  I've filed a bug with the owner here: https://github.com/terinjokes/terinstock.com/issues/2

**Comment by broofa** [comment]
Looks like the npmjs.cf issue is resolved.  Please try again and let me know if this is still an issue.

**Comment by WiseBird** [comment]
Now I see other error:
![image](https://user-images.githubusercontent.com/1745378/35043571-2c359058-fb9e-11e7-9473-bcbb1a083614.png)
![image](https://user-images.githubusercontent.com/1745378/35043617-5001dbcc-fb9e-11e7-83b9-65a134e92884.png)

**Comment by broofa** [comment]
Hmm.  I'm not seeing this error.  What URL are you hitting? What's the browser/useragent?

If Firefox, make sure you have `dom.moduleScripts.enabled` in the about:config page.

**Comment by broofa** [comment]
Ah, 'found the problem.  This is happening when dropping a `package.json` file.
