### ISSUE TITLE
Use a more pleasant color scheme

### ISSUE THREAD

**Issue by fregante** [broofa/npmgraph#30]
I haven't used `npmgraph` in a while but I'm pleasantly surprised by what it can do now!

However the military green is a little off-putting, would you consider using a [fresher color palette](https://colorhunt.co/)?

**Comment by broofa** [comment]
Colors are a notoriously subjective topic.  Feel free to suggest a different palette.  The base colors are [defined here](https://github.com/broofa/npmgraph/blob/master/index.css#L5-L19).  As you can see, I found the coolors.co site to be useful.
