### ISSUE TITLE
Highlight related nodes when selecting one of them

### ISSUE THREAD

**Issue by stof** [broofa/npmgraph#31]
Sometimes, arrows are not easy to follow due to overlap. It would be great if selecting a node could highlight the related nodes (both dependants and dependers, in different color). This would make it easier to use for situations like these screenshots:

A bunch of packages sharing common dependencies:
![image](https://user-images.githubusercontent.com/439401/99706187-ffceb880-2a9a-11eb-8122-4e223c90103a.png)

Packages being drawn misaligned with their dependencies and so curved edges overlapping a lot (this case might be avoided by reorganizing nodes though)
![image](https://user-images.githubusercontent.com/439401/99706415-4ae8cb80-2a9b-11eb-89a9-ca09a60997ab.png)

**Comment by broofa** [comment]
Agreed.  I'vebeen meaning to implement this for awhile now but just haven't had the time.  A PR would be well received.

**Comment by broofa** [comment]
Selecting a node now highlights the connected lines as well as the node
