### ISSUE TITLE
NPMS.io meta data only supports 250 or less packages in one call

### ISSUE THREAD

**Issue by lil5** [broofa/npmgraph#33]
```json
{"code":"INVALID_PARAMETER","message":"\"names\" must contain less than or equal to 250 items"}
```

### Steps to reproduce:

**1. Use this link as an example:**
http://npm.broofa.com/?q=@vue/cli-plugin-babel

**2. Open the web inspector and click on the network tab**

**3. Select `NPMS.io maintenance score` in the "Colorize by" select option.**

**4. Read the result from POST `https://api.npms.io/v2/package/mget`**

**Comment by broofa** [comment]
Can you try again?  This is working for me.  Also, I pushed out a new release around the time you filed this that should fix the problem.  (You may need to clear cache?)

**Comment by broofa** [comment]
Let me know if this is still a problem and I'll reopen

**Comment by lil5** [comment]
Yes this is fixed. Thanks 🎉
