### ISSUE TITLE
Support search/filtering

### ISSUE THREAD

**Issue by fregante** [broofa/npmgraph#35]
I just uploaded [my package.json](https://github.com/sindresorhus/refined-github/blob/master/package.json) and enabled devDependencies. Needless to say, finding things is a little hard: 

<img width="161" alt="Screen Shot 1" src="https://user-images.githubusercontent.com/1402241/103454242-a10a7a80-4ca7-11eb-9a70-0a636e9b56d9.png">

There are a few ways to make this easier:

- Adding a field above this list so that it can filter it and I can click one of the modules (which isn't currently fully working, it scrolls to the bottom left of the graph)
	
	<img width="414" alt="Screen Shot 2" src="https://user-images.githubusercontent.com/1402241/103454299-3efe4500-4ca8-11eb-82f7-26fd4a562a42.png">

- Double-clicking on a module in the graph could "focus" on it, maybe simply by opening an explorer for that module in a new tab
- Hiding a dependency and all of its subs from the graph. There are just a few dependencies that ruin it for everyone else (like parcel-bundler with its 693 non-dev dependencies!)

**Comment by broofa** [comment]
Replying with some iniitial impressions here, but can you break these out into separate issues?  Specifically...

> Adding a field above this list so that it can filter it**

I've tried to design the UI in a way that allows you to leverage the browser's built-in "Find" capabilities.  E.g. ⌘-F -> "babel"
.

> "(which isn't currently fully working, it scrolls to the bottom left of the graph)"**

What browser are you using?  This is working for me in Chrome (at least, on other large graphs, like `request` + devDependencies.)  Clicking a module in the Inspector selects it and scrolls it into view in the graph.

> Double-clicking on a module in the graph could "focus" on it

Yup, good catch.  This is actually a regression. (This used to work before I switched to preact for the UI).

**Comment by fregante** [comment]
> (Obligatory slap on the wrist for ["If you have multiple issues, please file separate bug reports"](https://developer.mozilla.org/en-US/docs/Mozilla/QA/Bug_writing_guidelines#How_to_report_a_bug). 😄

Ouch!



> lean on the built-in browser "Find" feature for this sort of thing

That's good, however it won't hide non-matching modules like a filter would. Perhaps #39 can be a replacement.
