### ISSUE TITLE
Double-clicking on a module in the graph could "focus" on it

### ISSUE THREAD

**Issue by fregante** [broofa/npmgraph#38]
On large dependency trees it'd be useful to focus/extract only one dependency and its subs. This could happen on double-click on the tree or sidebar, by opening a new tab or just replacing the current tree (but it needs to be ctrl-z-able)

**Comment by broofa** [comment]
Made module name in the Module inspector tab clickable to drill in to the graph for that module:
![image](https://user-images.githubusercontent.com/164050/103677052-adf0cd80-4f36-11eb-8034-8c903b61d9cf.png)

This isn't exactly the double-click behavior you requested, but it's how I used to have this implemented, and leaves the double click action open for selecting the module name, or expanding/collapsing a module in the graph, or whatever.  If you feel strongly about how this I'm happy to discuss.

FWIW, I fixed up the history push/popstate code navigating in / out of modules in a graph should be reasonably performant (doesn't need to re-fetch module info from NPM repository)

**Comment by fregante** [comment]
Yeah that’s even better, thanks!
