### ISSUE TITLE
Show status (rendering, loading, etc)

### ISSUE THREAD

**Issue by fregante** [broofa/npmgraph#40]
I noticed a long wait when clicking `Show devDependencies` in my package.json and you also seem to not like blocking the UI. I think that showing a little tab saying "Something is happening" would make it more bearable.

Personally I don't mind, but I don't want my wrist [slapped](https://github.com/broofa/npmgraph/issues/35#issuecomment-753477670) again by suggesting it in #39

**Comment by broofa** [comment]
Yeah, this bugs me as well.  d3-graphviz has [some events](https://github.com/magjac/d3-graphviz#graphviz_on), but no real progress events.  Let me see what I can do.

**Comment by fregante** [comment]
No need for full disclosure, just "processing…" would be good enough so that it doesn't look like the program is locked.
