### ISSUE TITLE
Activate TLS certs enable HTTPS by default

### ISSUE THREAD

**Issue by Krinkle** [broofa/npmgraph#42]
I've on more than one occasion seen a link to <https://npm.broofa.com/>, presumably by accident, out of habit, or perhaps due to some tools defaulting to HTTPS if no scheme is specified.

This is a request to kindly consider activate TLS on the server, and perhaps redirect to and/or promote by default the HTTPS variant in the README and repo description here on GitHub.

From the error page, it appears that the site is hosted at Dreamhost, which has a guide for [using Let's Encrypt](https://help.dreamhost.com/hc/en-us/articles/216539548-Adding-a-free-Let-s-Encrypt-certificate) that might be helpful, and seems it will automatically use [HTTPS by default](https://help.dreamhost.com/hc/en-us/articles/115003505112-How-to-force-your-site-to-redirect-to-https-SSL-).

**Comment by broofa** [comment]
Done.
