### ISSUE TITLE
Not working in Safari (14)

### ISSUE THREAD

**Issue by fregante** [broofa/npmgraph#43]
<img width="784" alt="Screen Shot 3" src="https://user-images.githubusercontent.com/1402241/104521263-26543000-55c2-11eb-844c-f4dd10736bc4.png">

No page works, no errors in the console

**Comment by fregante** [comment]
Weird, it works now!

**Comment by broofa** [comment]
Maybe a browser cache issue?  (The current deploy process doesn't rename the various JS and CSS resources, so sometimes  a shift+refresh is needed.)

**Comment by fregante** [comment]
Indeed, it happened again and it was ok after a refresh. Can this be solved?
