### ISSUE TITLE
"*" references in package.json fail

### ISSUE THREAD

**Issue by dtgriscom** [broofa/npmgraph#6]
If you load a `package.json` file where any packages have versions specified as `"*"`, then npmgraph will fail to handle those packages, presenting them as invalid references. (Yes, this is generally a bad thing for the `package.json` owner to do, but it's legal, and npmgraph should probably handle it.)

**Comment by broofa** [comment]
Can you verify this is still an issue and, If so, can you provide the module name so I can reproduce?

**Comment by broofa** [comment]
Fixed in a40a3c0b52a265b53c0651f594060bef995e1547
